### ISSUE TITLE
col-sort value with semicolon throws an error

### ISSUE THREAD

**Issue by Thanood** [vegarringdal/aureliaGrid#65]
When I create a grid column like this:

```html
<v-grid-col col-width="200" col-add-row-attributes="readonly='true';" col-pin-left="true" col-sort="field: commonName" col-filter="commonName|*" col-field="commonName"></v-grid-col>
```

(not the semicolon in `col-sort`)
I'm getting an error `TypeError: Cannot read property 'split' of null` in `ViewCompiler` - not sure which line of the grid code it is.

This works in custom html columns: `v-sort="field: assignmentCounts.roles; asc: false;"`

**Comment by Thanood** [comment]
```
Unhandled rejection TypeError: Cannot read property 'split' of null
    at TemplatingBindingLanguage.inspectAttribute (http://localhost:9000/scripts/vendor-bundle.js:23752:27)
    at SyntaxInterpreter.options (http://localhost:9000/scripts/vendor-bundle.js:23636:27)
    at SyntaxInterpreter.interpret (http://localhost:9000/scripts/vendor-bundle.js:23571:34)
    at TemplatingBindingLanguage.createAttributeInstruction (http://localhost:9000/scripts/vendor-bundle.js:23799:46)
    at ViewCompiler._compileElement (http://localhost:9000/scripts/vendor-bundle.js:21214:41)
    at ViewCompiler._compileNode (http://localhost:9000/scripts/vendor-bundle.js:21000:23)
    at ViewCompiler._compileElement (http://localhost:9000/scripts/vendor-bundle.js:21292:31)
    at ViewCompiler._compileNode (http://localhost:9000/scripts/vendor-bundle.js:21000:23)
    at ViewCompiler._compileNode (http://localhost:9000/scripts/vendor-bundle.js:21022:33)
    at ViewCompiler.compile (http://localhost:9000/scripts/vendor-bundle.js:20969:12)
    at HtmlBehaviorResource.compile (http://localhost:9000/scripts/vendor-bundle.js:22381:46)
    at ViewCompiler._compileElement (http://localhost:9000/scripts/vendor-bundle.js:21262:40)
    at ViewCompiler._compileNode (http://localhost:9000/scripts/vendor-bundle.js:21000:23)
    at ViewCompiler._compileNode (http://localhost:9000/scripts/vendor-bundle.js:21022:33)
    at ViewCompiler.compile (http://localhost:9000/scripts/vendor-bundle.js:20969:12)
    at ColumnMarkup.getHeaderViews (http://localhost:9000/scripts/vendor-bundle.js:29186:38)
From previous event:
    at Aurelia.setRoot (http://localhost:9000/scripts/vendor-bundle.js:12741:42)
    at http://localhost:9000/scripts/app-bundle.js:102:22
From previous event:
    at Object.configure (http://localhost:9000/scripts/app-bundle.js:101:21)
    at http://localhost:9000/scripts/vendor-bundle.js:6009:22
From previous event:
    at config (http://localhost:9000/scripts/vendor-bundle.js:6004:48)
    at handleApp (http://localhost:9000/scripts/vendor-bundle.js:5995:12)
    at http://localhost:9000/scripts/vendor-bundle.js:6028:13
From previous event:
    at http://localhost:9000/scripts/vendor-bundle.js:6026:40
From previous event:
    at http://localhost:9000/scripts/vendor-bundle.js:6025:29
From previous event:
    at run (http://localhost:9000/scripts/vendor-bundle.js:6021:26)
    at Object.<anonymous> (http://localhost:9000/scripts/vendor-bundle.js:6048:3)
    at Object.execCb (http://localhost:9000/scripts/vendor-bundle.js:5449:33)
    at Object.check (http://localhost:9000/scripts/vendor-bundle.js:4637:51)
    at Object.enable (http://localhost:9000/scripts/vendor-bundle.js:4929:22)
    at Object.enable (http://localhost:9000/scripts/vendor-bundle.js:5310:39)
    at Object.<anonymous> (http://localhost:9000/scripts/vendor-bundle.js:4914:33)
    at http://localhost:9000/scripts/vendor-bundle.js:3890:23
    at each (http://localhost:9000/scripts/vendor-bundle.js:3815:31)
    at Object.enable (http://localhost:9000/scripts/vendor-bundle.js:4866:17)
    at Object.init (http://localhost:9000/scripts/vendor-bundle.js:4542:26)
    at http://localhost:9000/scripts/vendor-bundle.js:5213:36
```

**Comment by vegarringdal** [comment]
Please update grid, and try again

**Comment by vegarringdal** [comment]
This should be fixed now, reopen if not
